server:
  port: 6000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ferctiy/ConfigServer.git
          search-paths: config-repo
          username: 992611060@qq.com
          password: lpg992611060
